# Generated by Django 2.2.3 on 2019-08-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='user_profile',
            new_name='created_by',
        ),
    ]
