# Generated by Django 2.1.7 on 2019-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_auto_20190417_0950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followingmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='followingmodel',
            name='following_by',
        ),
        migrations.RemoveField(
            model_name='followingmodel',
            name='following_to',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='FollowingModel',
        ),
        migrations.DeleteModel(
            name='RecipeModel',
        ),
    ]
