# Generated by Django 2.1.7 on 2019-05-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_auto_20190423_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_actvie',
            new_name='is_active',
        ),
    ]
